name: Build and Publish
on:
  workflow_call: {}
  push:
    branches: [master]
jobs:
  buildPublish:
    name: Build & Publish
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'true'
      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'
      - run: sudo apt-get install -y pkgdiff
      - name: 'Get latest package version'
        id: 'getVersion'
        run: |
          echo "package_json_version=$(jq -r '.version' < sheetjs/package.json)" >> $GITHUB_OUTPUT
          echo "latest_published_version=$(cat latest_published.txt)" >> $GITHUB_OUTPUT
      - run: ./build.sh
        if: steps.getVersion.outputs.package_json_version != steps.getVersion.outputs.latest_published_version
      - name: Upload PkgDiff Reports on Failure
        if: failure()  # Runs only if the previous step fails
        uses: actions/upload-artifact@v4
        with:
          name: pkgdiff_reports
          path: pkgdiff_reports/
      - run: ./publish.sh
        if: steps.getVersion.outputs.package_json_version != steps.getVersion.outputs.latest_published_version
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
      - run: git submodule foreach --recursive git reset --hard
      - uses: stefanzweifel/git-auto-commit-action@v5
        if: steps.getVersion.outputs.package_json_version != steps.getVersion.outputs.latest_published_version
        with:
          commit_message: 'Publish ${{ steps.getVersion.outputs.package_json_version }}'
