name: Build and Publish
on:
  workflow_call: {}
  push:
    branches: [test-workflow]
jobs:
  buildPublish:
    name: Build & Publish
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'true'
      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'
      - run: sudo apt-get install -y pkgdiff
      - name: 'Get latest package version'
        id: 'getVersion'
        run: >
          echo "package_json_version=$(jq -r '.version' < sheetjs/package.json)" >> $GITHUB_OUTPUT
          echo "latest_published_version=$(cat latest_published.txt)" >> $GITHUB_OUTPUT
      - run: ./build.sh
        if: steps.getVersion.outputs.package_json_version != steps.getLatestPublishedVersion.outputs.latest_published_version
      - run: echo "test"
